title: Vickie Poynter's blog 
description: Vickie from Greenwood, Indiana

url: https://vickiep.github.com.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: <img class="img-circle" src="/assets/img/profile_picture_2018.jpg" alt=""/>
   url: /index.html
 - title: Home
   url: /index.html
 - title: Blogs
   url: /blogs
 - title: Shared-By-Neighbors
   url: /neighbors
 - title: Documents
   url: /documents
 - title: Contact Me
   url: /contact

social:
   github: vickiep
   email: poynterv@sbcglobal.net

google_analytics: "UA-58263416-1"
